In [4]:
import numpy as np
from sklearn.utils import shuffle
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [20]:
test_labels= []
test_samples= []

In [21]:
for i in range(50):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    random_older=randint(65,100)
    test_samples.append(random_older)
    test_labels.append(0)
    
for i in range(1000):
    random_younger=randint(13,64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    random_older=randint(65,100)
    test_samples.append(random_older)
    test_labels.append(1)

In [24]:
test_labels=np.array(test_labels)
test_samples=np.array(test_samples)
test_labels,test_samples=shuffle(test_labels,test_samples)

In [25]:
scale=MinMaxScaler(feature_range=(0,1))
scaled_test_samples=scale.fit_transform(test_samples.reshape(-1,1))

Validation set

In [12]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense, BatchNormalization, Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

In [1]:
model=Sequential([
    Dense(units=16,input_shape=(1,),activation='relu'),
    Dense(units=32,activation='relu'),
    Dense(units=2,activation='softmax'),
])

NameError: name 'Sequential' is not defined

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(optimizer=Adam(learning_rate=0.0001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(x=scaled_test_samples,y=test_labels,batch_size=10,epochs=20,shuffle=True,verbose=2)

Epoch 1/20
210/210 - 1s - loss: 0.2768 - accuracy: 0.9362 - 1s/epoch - 7ms/step
Epoch 2/20
210/210 - 1s - loss: 0.2739 - accuracy: 0.9362 - 600ms/epoch - 3ms/step
Epoch 3/20
210/210 - 1s - loss: 0.2716 - accuracy: 0.9386 - 503ms/epoch - 2ms/step
Epoch 4/20
210/210 - 1s - loss: 0.2694 - accuracy: 0.9390 - 555ms/epoch - 3ms/step
Epoch 5/20
210/210 - 1s - loss: 0.2675 - accuracy: 0.9376 - 568ms/epoch - 3ms/step
Epoch 6/20
210/210 - 1s - loss: 0.2658 - accuracy: 0.9390 - 602ms/epoch - 3ms/step
Epoch 7/20
210/210 - 1s - loss: 0.2642 - accuracy: 0.9400 - 525ms/epoch - 3ms/step
Epoch 8/20
210/210 - 1s - loss: 0.2628 - accuracy: 0.9390 - 582ms/epoch - 3ms/step
Epoch 9/20
210/210 - 1s - loss: 0.2617 - accuracy: 0.9400 - 644ms/epoch - 3ms/step
Epoch 10/20
210/210 - 1s - loss: 0.2606 - accuracy: 0.9429 - 535ms/epoch - 3ms/step
Epoch 11/20
210/210 - 1s - loss: 0.2595 - accuracy: 0.9390 - 577ms/epoch - 3ms/step
Epoch 12/20
210/210 - 1s - loss: 0.2583 - accuracy: 0.9429 - 644ms/epoch - 3ms/step
Epoc

In [27]:
predictions=model.predict(x=scaled_test_samples,batch_size=10,verbose=0)

In [17]:
for i in predictions:
    print(i)

[0.93378705 0.06621292]
[0.92694247 0.07305754]
[0.20021789 0.7997821 ]
[0.01962835 0.98037165]
[0.2632656 0.7367344]
[0.31177858 0.68822145]
[0.04524156 0.95475847]
[0.03483927 0.9651608 ]
[0.7514114 0.2485886]
[0.12152696 0.878473  ]
[0.03483927 0.9651608 ]
[0.04524156 0.95475847]
[0.03483927 0.9651608 ]
[0.04957179 0.95042825]
[0.92629296 0.07370707]
[0.42132798 0.57867205]
[0.930173   0.06982697]
[0.21988954 0.7801104 ]
[0.8603131  0.13968685]
[0.02947031 0.9705296 ]
[0.05429291 0.9457071 ]
[0.82929605 0.17070393]
[0.5392114  0.46078852]
[0.45048746 0.54951257]
[0.8864659  0.11353409]
[0.92694247 0.07305754]
[0.93449956 0.06550045]
[0.90665334 0.09334663]
[0.08017744 0.9198226 ]
[0.28690973 0.71309024]
[0.03792199 0.962078  ]
[0.92364126 0.07635867]
[0.7930486  0.20695142]
[0.16490453 0.83509547]
[0.6792407 0.3207593]
[0.93378705 0.06621292]
[0.33778197 0.662218  ]
[0.9275867  0.07241327]
[0.7930486  0.20695142]
[0.9262135  0.07378652]
[0.36480463 0.6351953 ]
[0.9275867  0.07241327

In [28]:
round_pred=np.argmax(predictions,axis=1)
for i in round_pred:
    print(i)

1
1
1
0
0
0
1
1
0
0
0
1
0
0
1
0
0
0
1
0
0
1
0
0
1
0
0
0
1
0
0
0
0
0
0
1
0
1
1
0
1
1
1
0
1
0
1
0
1
0
0
1
1
1
1
0
1
0
1
0
0
1
0
0
1
1
1
0
0
1
0
1
1
0
1
1
0
1
1
1
1
1
1
1
0
0
0
0
1
0
1
1
1
0
0
1
0
1
0
0
1
0
0
1
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
0
1
0
0
1
0
0
0
0
0
1
0
1
0
0
0
0
1
0
0
0
0
1
1
0
0
0
0
1
1
0
0
1
1
0
1
0
1
0
1
0
0
1
0
1
0
0
1
0
1
1
1
0
1
0
1
0
1
0
1
1
1
1
0
1
0
0
0
0
0
0
1
0
0
1
1
1
1
1
0
1
0
1
0
1
0
1
0
1
1
0
1
0
0
1
1
0
0
1
1
1
0
1
0
0
0
1
1
1
1
0
0
0
0
0
1
0
0
1
0
0
0
1
0
0
1
0
0
0
0
0
1
1
0
1
1
1
0
1
0
1
1
0
1
0
1
1
0
1
0
0
0
0
0
0
1
0
0
1
0
1
1
0
0
0
0
1
0
0
1
1
1
1
0
0
1
1
0
0
0
0
1
0
0
1
0
0
0
0
1
0
1
0
1
0
1
0
0
0
1
0
0
1
0
0
1
0
1
0
1
0
0
0
0
1
0
1
0
1
0
0
0
0
1
1
1
0
0
1
0
1
0
0
0
0
1
1
0
0
1
0
1
0
0
1
1
1
1
1
0
1
1
0
1
1
1
0
0
0
0
0
0
1
0
0
1
0
1
0
0
0
0
1
1
1
1
1
1
1
0
0
0
1
1
0
0
0
1
0
0
1
1
1
0
1
1
1
1
0
1
1
1
1
0
0
1
0
1
1
0
0
0
0
0
1
1
1
1
1
0
1
0
1
0
1
0
1
1
1
0
0
0
0
0
0
1
1
1
1
0
1
0
0
0
1
1
1
0
1
1
1
1
1
1
0
1
0
0
1
0
0
0
0
1
0
0
0
1
1
1
0
0
1
1
0
0


In [29]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
%matplotlib inline

In [31]:
cm=confusion_matrix(y_true=test_labels,y_pred=round_pred)
cm

array([[ 980,   70],
       [  50, 1000]], dtype=int64)

Saving

In [32]:
import os.path

In [35]:
if os.path.isfile('models/medical_trial') is False:
    model.save('models/medical_trial')

INFO:tensorflow:Assets written to: models/medical_trial\assets


INFO:tensorflow:Assets written to: models/medical_trial\assets


In [36]:
from tensorflow.keras.models import load_model
new_model=load_model('models/medical_trial')

In [37]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [38]:
new_model.get_weights()

[array([[ 0.28058738, -0.19075248, -0.17858332,  0.50540185, -0.41814032,
          0.3604924 ,  0.20399491, -0.4205315 ,  0.48908788,  0.33479118,
         -0.28811008,  0.5895835 , -0.3132345 , -0.38716924,  0.24250744,
          0.449572  ]], dtype=float32),
 array([-0.11420403,  0.        ,  0.        , -0.16266954,  0.        ,
        -0.13640077, -0.08684655,  0.        , -0.13868429,  0.1848783 ,
         0.        , -0.15472136,  0.        ,  0.        , -0.04410953,
         0.11470077], dtype=float32),
 array([[ 3.28025967e-01, -6.04193926e-01,  2.12457910e-01,
          5.40950775e-01, -6.47939563e-01,  2.39653185e-01,
          1.92204624e-01,  2.79402696e-02, -1.62924871e-01,
          1.43396363e-01, -5.58594644e-01, -3.13813180e-01,
         -2.72193015e-01,  2.34986708e-01,  2.89735138e-01,
          1.52099505e-01, -6.37227714e-01,  4.99272287e-01,
         -1.42444536e-01,  3.24466825e-01,  5.40208578e-01,
         -3.79407823e-01,  1.36974126e-01, -6.95334887e-03,
 

In [39]:
new_model.optimizer

In [40]:
#save as JSON
json_string=model.to_json()

In [41]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 1], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "batch_input_shape": [null, 1], "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_r

In [43]:
from tensorflow.keras.models import model_from_json
model_architecture=model_from_json(json_string)

In [45]:
model_architecture.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                32        
                                                                 
 dense_1 (Dense)             (None, 32)                544       
                                                                 
 dense_2 (Dense)             (None, 2)                 66        
                                                                 
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [46]:
#model.save_weights('/path')
#only to save weights
#create dense network again as model2 with same layers
#load_weights and saveweights